### ISSUE TITLE
Sumar contenido aprobado en las vistas de V0

### ISSUE THREAD

**Issue by mechafiz** [gobabiertoAR/ckan#37]
PORTAL- Contenido que nos falta definir:
-Vista Landing
      Titulo y bajada
      Grupos: Falta definir urbanismo. 

      Contenido

-Vista Estática
      Faltan todavía los textos

-Vista sección Datos:
     Bajada con explicación de la sección

-Vista sección Organizaciones:
     Bajada con explicación de la sección

-Vista Dataset:
     Va actividad reciente
     

-Vista Metadata:
     Campos de info adicional

Dataset

last updated-creación

Recurso

last updated-creación-formato

**Comment by chadad** [comment]
Chicos:  Definiciones:

Redes 
https://github.com/gobabiertoAR

-Github

- Facebook

https://www.facebook.com/GobAbiertoAR/

- Twitter

https://twitter.com/datosarg
